version: '3'

services:

  mongo:
    image: mongo:latest
    restart: always
    container_name: mongo_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongoDB2022!
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db

  api:
    container_name: clean-node-api
    build: .
    restart: always
    command: npm start
    ports:
      - 5050:5050
    volumes:
      - ./dist:/usr/src/clean-node-api/dist
    links:
      - mongo
