version: '3'

services:

  mongo:
    image: mongo:latest
    restart: always
    container_name: mongo-container
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: mongoDB2022!
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db

  api:
    container_name: api-container
    build: .
    image: clean-node-api
    restart: always
    command: npm run debug
    volumes:
      - ./dist:/usr/src/clean-node-api/dist
      - ./package.json:/usr/src/clean-node-api/package.json
    ports:
      - 5050:5050
      - 9222:9222
    links:
      - mongo
